name: www2.ourphone.tf
on:
  push:
    branches: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www2.ourphone.tf
      uses: appleboy/ssh-action@master
      with:
        host: www2.ourphone.tf
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www2/www_ourphone/
          git log -1
          git restore .
          git pull
          sed -i "s/https:\/\/ourphone.tf/https:\/\/www2.ourphone.tf/g" config.toml
          ./build.sh
